/*
 * blancoDb
 * Copyright (C) 2004-2006 Yasuo Nakanishi
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */
package blanco.db.util;

import blanco.cg.BlancoCgObjectFactory;
import blanco.cg.valueobject.*;
import blanco.commons.util.BlancoNameAdjuster;
import blanco.db.common.stringgroup.BlancoDbLoggingModeStringGroup;
import blanco.db.common.valueobject.BlancoDbSetting;
import blanco.db.expander.query.BlancoPerfomanceCommonUtil;

import java.util.List;

/**
 * blancoDbが共通的に利用するユーティリティクラス。
 *
 * このクラスが生成するクラスはblancoDbが生成したソースコードで利用されます
 *
 * @since 2020.09.04
 * @author tueda
 */
public class BlancoDbDynamicClauseClassJava {
    /**
     * このクラス自身のクラス名
     */
    public static final String CLASS_NAME = "BlancoDbDynamicClause";

    /**
     * blancoCg オブジェクトファクトリ。
     */
    private BlancoCgObjectFactory fCgFactory = null;

    /**
     * このクラスが含まれるソースコード。
     */
    private BlancoCgSourceFile fCgSourceFile = null;

    private BlancoDbSetting fDbSetting = null;

    public BlancoDbDynamicClauseClassJava(final BlancoCgObjectFactory cgFactory,
                                          final String argPackage, final BlancoDbSetting argDbSetting) {
        fCgFactory = cgFactory;
        fCgSourceFile = fCgFactory.createSourceFile(argPackage,
                "This code is generated by blanco Framework.");

        this.fDbSetting = argDbSetting;
    }

    public BlancoCgSourceFile expand() {
        final BlancoCgClass cgClass = fCgFactory.createClass(CLASS_NAME, null);
        fCgSourceFile.getClassList().add(cgClass);

        {
            final List<String> listDesc = cgClass.getLangDoc()
                    .getDescriptionList();

            listDesc.add("動的条件句を定義するクラス。");
            listDesc.add("");
            listDesc.add("このクラスはblancoDbが生成したソースコードで利用されます <br>");
            listDesc
                    .add("このクラスは blancoDbが生成したソースコードから利用されます。直接呼び出すことは推奨されません。");
            listDesc.add("");
            listDesc.add("@since 2020.09.01");
            listDesc.add("@author blanco Framework");
        }

        {
            /* fields */
            cgClass.getFieldList().add(
                    buildField("tag", "タグ名")
            );
            cgClass.getFieldList().add(
                    buildField("condition", "条件句タイプ")
            );
            cgClass.getFieldList().add(
                    buildField("items", "対象Items", "java.util.List", "java.lang.String", "null")
            );
            cgClass.getFieldList().add(
                    buildField("comparison", "比較演算子")
            );
            cgClass.getFieldList().add(
                    buildField("logical", "論理演算子（先導）")
            );
            cgClass.getFieldList().add(
                    buildField("type", "値の型")
            );
        }

        {
            /* constructors */
            cgClass.getMethodList().add(
                    buildConstructor("DEFAULT")
            );
            cgClass.getMethodList().add(
                    buildConstructor("ORDERBY")
            );
            cgClass.getMethodList().add(
                    buildConstructor("NOTCOMPARE")
            );
            cgClass.getMethodList().add(
                    buildConstructor("COMPARE")
            );
            cgClass.getMethodList().add(
                    buildConstructor("LITERAL")
            );
        }

        {
            /* Getter/Setter */
            cgClass.getMethodList().add(
                    buildMethodSet("tag", "タグ名")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("tag", "タグ名")
            );

            cgClass.getMethodList().add(
                    buildMethodSet("condition", "条件句タイプ")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("condition", "条件句タイプ")
            );

            cgClass.getMethodList().add(
                    buildMethodSet("items", "対象Item", "java.util.List", "java.lang.String")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("items", "対象Item", "java.util.List", "java.lang.String")
            );

            cgClass.getMethodList().add(
                    buildMethodSet("comparison", "比較演算子")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("comparison", "比較演算子")
            );

            cgClass.getMethodList().add(
                    buildMethodSet("logical", "論理演算子（先導）")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("logical", "論理演算子（先導）")
            );

            cgClass.getMethodList().add(
                    buildMethodSet("type", "値の型")
            );
            cgClass.getMethodList().add(
                    buildMethodGet("type", "値の型")
            );

            cgClass.getMethodList().add(
                    buildMethodItems()
            );
            cgClass.getMethodList().add(
                    buildMethodGetItem()
            );
        }

        if (fDbSetting.getLogging()) {
            switch (fDbSetting.getLoggingMode()) {
                case BlancoDbLoggingModeStringGroup.PERFORMANCE:
                case BlancoDbLoggingModeStringGroup.SQLID:
                    BlancoPerfomanceCommonUtil.addPerfomanceFieldMethod(fCgFactory,
                            fCgSourceFile, cgClass);
                    break;
            }
        }

        return fCgSourceFile;
    }

    private BlancoCgField buildField(
            final String name,
            final String desc
    ) {
        final BlancoCgField cgField = fCgFactory.createField(name, "java.lang.String", desc);
        cgField.setDefault("null");
        cgField.setAccess("private");
        return cgField;
    }

    private BlancoCgMethod buildConstructor(String type) {
        final BlancoCgMethod cgMethod = fCgFactory.createMethod(CLASS_NAME, "コンストラクタ");
        cgMethod.setConstructor(true);

        if ("DEFAULT".equals(type)) {
            return cgMethod;
        }

        final List<String> lineList = cgMethod.getLineList();

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argTag", "java.lang.String", "タグ名"));
        lineList.add("this.tag = argTag;");

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argCondition", "java.lang.String", "条件句タイプ"));
        lineList.add("this.condition = argCondition;");

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argItem", "java.lang.String", "対象Item"));
        lineList.add("this.items = this.parseItems(argItem);");

        if ("LITERAL".equals(type)) {
            cgMethod.getParameterList().add(
                    fCgFactory.createParameter("argRawItem", "java.lang.Boolean", "true の場合、対象Itemをカンマ区切りでparseしない"));
            lineList.add("if (argRawItem) {");
            lineList.add("this.items = new java.util.ArrayList<>();");
            lineList.add("items.add(argItem);");
            lineList.add("} else {");
            lineList.add("this.items = this.parseItems(argItem);");
            lineList.add("}");
            return cgMethod;
        }

        if ("ORDERBY".equals(type)) {
            return cgMethod;
        }

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argLogical", "java.lang.String", "論理演算子（先導）"));
        lineList.add("this.logical = argLogical;");

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argType", "java.lang.String", "値の型"));
        lineList.add("this.type = argType;");

        if (!"COMPARE".equals(type)) {
            return cgMethod;
        }

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("argComparison", "java.lang.String", "比較演算子"));
        lineList.add("this.comparison = argComparison;");

        return cgMethod;
    }

    private BlancoCgMethod buildMethodSet(
            final String name,
            final String desc) {
        // おのおののフィールドに対するセッターメソッドを生成します。
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("set" + BlancoNameAdjuster.toClassName(name), desc);

        cgMethod.getParameterList().add(
                fCgFactory.createParameter("arg" + BlancoNameAdjuster.toClassName(name),
                        "java.lang.String", desc)
        );

        // メソッドの実装
        cgMethod.getLineList().add(
                "this." + name + " = " + "arg" + BlancoNameAdjuster.toClassName(name) + ";"
        );
        return cgMethod;
    }

    private BlancoCgMethod buildMethodGet(
            final String name,
            final String desc) {
        // おのおののフィールドに対するゲッターメソッドを生成します。
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("get" + BlancoNameAdjuster.toClassName(name), desc);

        cgMethod.setReturn(fCgFactory.createReturn("java.lang.String", desc));

        // メソッドの実装
        cgMethod.getLineList().add(
                "return this." + name + ";");

        return cgMethod;
    }

    private BlancoCgField buildField(
            final String name,
            final String desc,
            final String type,
            final String generic,
            final String defaultValud
    ) {
        final BlancoCgField cgField = fCgFactory.createField(name, type, desc);
        cgField.setAccess("private");
        if (generic != null && generic.length() > 0) {
            cgField.getType().setGenerics(generic);
        }
        cgField.setDefault(defaultValud);
        return cgField;
    }

    private BlancoCgMethod buildMethodSet(
            final String name,
            final String desc,
            final String type,
            final String generic
    ) {
        // おのおののフィールドに対するセッターメソッドを生成します。
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("set" + BlancoNameAdjuster.toClassName(name), desc);

        BlancoCgParameter parameter = fCgFactory.createParameter("arg" + BlancoNameAdjuster.toClassName(name), type, desc);
        if (generic != null && generic.length() > 0) {
            parameter.getType().setGenerics(generic);
        }
        cgMethod.getParameterList().add(parameter);

        // メソッドの実装
        cgMethod.getLineList().add(
                "this." + name + " = " + "arg" + BlancoNameAdjuster.toClassName(name) + ";"
        );
        return cgMethod;
    }

    private BlancoCgMethod buildMethodGet(
            final String name,
            final String desc,
            final String type,
            final String generic
    ) {
        // おのおののフィールドに対するゲッターメソッドを生成します。
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("get" + BlancoNameAdjuster.toClassName(name), desc);

        cgMethod.setReturn(fCgFactory.createReturn(type, desc));
        if (generic != null && generic.length() > 0) {
            cgMethod.getReturn().getType().setGenerics(generic);
        }

        // メソッドの実装
        cgMethod.getLineList().add(
                "return this." + name + ";");

        return cgMethod;
    }

    private BlancoCgMethod buildMethodItems() {
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("parseItems", "カンマ区切りで指定された対象itemを文字列のリストに投入します。");
        BlancoCgParameter parameter = fCgFactory.createParameter("argItem", "java.lang.String", "対象itemsに入力されたカンマ区切りのitemのリストです。");
        parameter.setFinal(true);
        cgMethod.getParameterList().add(
                parameter
        );
        cgMethod.setReturn(
                fCgFactory.createReturn("java.util.List", "itemのListです。")
        );
        cgMethod.getReturn().getType().setGenerics("java.lang.String");

        List<String> lineList = cgMethod.getLineList();
        lineList.add("java.util.List<java.lang.String> items = new java.util.ArrayList<>();");
        lineList.add("if (argItem != null && argItem.length() > 0) {");
        lineList.add("java.lang.String [] itemArray = argItem.split(\",\");");
        lineList.add("for (int i = 0; i < itemArray.length; i++) {");
        lineList.add("items.add(itemArray[i].trim());");
        lineList.add("}");
        lineList.add("}");
        lineList.add("return items;");

        return cgMethod;
    }

    private BlancoCgMethod buildMethodGetItem() {
        final BlancoCgMethod cgMethod = fCgFactory.createMethod("getItem", "定義済みのitem群からitemを選択します。");
        BlancoCgParameter parameter = fCgFactory.createParameter("argKey", "java.lang.String", "入力されたitemです。");
        parameter.setFinal(true);
        cgMethod.getParameterList().add(
                parameter
        );
        cgMethod.setReturn(
                fCgFactory.createReturn("java.lang.String", "指定されたitemが存在しなければ null を返します。")
        );

        List<String> lineList = cgMethod.getLineList();
        lineList.add("String item = null;");
        lineList.add("for (String defined : this.items) {");
        lineList.add("if (defined.equals(argKey)) {");
        lineList.add("item = defined;");
        lineList.add("break;");
        lineList.add("}");
        lineList.add("}");
        lineList.add("return item;");

        return cgMethod;
    }
}
